// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQhhZN5PHVxW7lTKykpFZIm_QT-NruHQo',
    appId: '1:917733271388:android:8d4ceb43a6527d65994399',
    messagingSenderId: '917733271388',
    projectId: 'fir-bfdfe',
    storageBucket: 'fir-bfdfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVeDyUJHbwHvEg1FJH-su8x-laazMjPU',
    appId: '1:917733271388:ios:b2b78d8a8930c3e1994399',
    messagingSenderId: '917733271388',
    projectId: 'fir-bfdfe',
    storageBucket: 'fir-bfdfe.appspot.com',
    androidClientId: '917733271388-53rmkldkefigcda3u1ddckgrkvr4pbkj.apps.googleusercontent.com',
    iosClientId: '917733271388-b4d7g1ookb8netjggbenge48j2cgrbrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokeApp',
  );
}
